package io.novafoundation.nova.feature_staking_impl.domain.validations.rebond

import io.novafoundation.nova.common.validation.Validation
import io.novafoundation.nova.common.validation.ValidationSystem
import io.novafoundation.nova.feature_wallet_api.domain.validation.PositiveAmountValidation
import io.novafoundation.nova.feature_wallet_api.domain.validation.EnoughAmountToTransferValidation

typealias RebondFeeValidation = EnoughAmountToTransferValidation<RebondValidationPayload, RebondValidationFailure>
typealias NotZeroRebondValidation = PositiveAmountValidation<RebondValidationPayload, RebondValidationFailure>

typealias RebondValidation = Validation<RebondValidationPayload, RebondValidationFailure>

typealias RebondValidationSystem = ValidationSystem<RebondValidationPayload, RebondValidationFailure>
