package io.novafoundation.nova.feature_crowdloan_impl.presentation.contribute.custom.moonbeam

import io.novafoundation.nova.feature_crowdloan_impl.presentation.contribute.custom.CustomContributeSubmitter

class MoonbeamCrowdloanSubmitter : CustomContributeSubmitter
