package io.novafoundation.nova.feature_staking_impl.domain.validations.unbond

import io.novafoundation.nova.common.validation.Validation
import io.novafoundation.nova.common.validation.ValidationSystem
import io.novafoundation.nova.feature_staking_impl.domain.validations.NotZeroAmountValidation
import io.novafoundation.nova.feature_staking_impl.domain.validations.UnbondingRequestsLimitValidation
import io.novafoundation.nova.feature_wallet_api.domain.validation.EnoughToPayFeesValidation

typealias UnbondFeeValidation = EnoughToPayFeesValidation<UnbondValidationPayload, UnbondValidationFailure>
typealias NotZeroUnbondValidation = NotZeroAmountValidation<UnbondValidationPayload, UnbondValidationFailure>
typealias UnbondLimitValidation = UnbondingRequestsLimitValidation<UnbondValidationPayload, UnbondValidationFailure>

typealias UnbondValidation = Validation<UnbondValidationPayload, UnbondValidationFailure>

typealias UnbondValidationSystem = ValidationSystem<UnbondValidationPayload, UnbondValidationFailure>
