package io.novafoundation.nova.feature_staking_impl.domain.validations.payout

import io.novafoundation.nova.feature_wallet_api.domain.validation.EnoughAmountToTransferValidation

typealias PayoutFeeValidation = EnoughAmountToTransferValidation<MakePayoutPayload, PayoutValidationFailure>
