package io.novafoundation.nova.feature_crowdloan_impl.domain.contribute.validations

import io.novafoundation.nova.common.validation.Validation
import io.novafoundation.nova.feature_wallet_api.domain.validation.EnoughToPayFeesValidation
import io.novafoundation.nova.feature_wallet_api.domain.validation.ExistentialDepositValidation

typealias ContributeValidation = Validation<ContributeValidationPayload, ContributeValidationFailure>

typealias ContributeEnoughToPayFeesValidation = EnoughToPayFeesValidation<ContributeValidationPayload, ContributeValidationFailure>
typealias ContributeExistentialDepositValidation = ExistentialDepositValidation<ContributeValidationPayload, ContributeValidationFailure>
