package io.novafoundation.nova.feature_staking_impl.domain.validations.balance

import io.novafoundation.nova.feature_staking_impl.domain.validations.AccountRequiredValidation
import io.novafoundation.nova.feature_staking_impl.domain.validations.UnbondingRequestsLimitValidation

const val BALANCE_REQUIRED_STASH = "BalanceAccountRequiredValidation.Stash"
const val BALANCE_REQUIRED_CONTROLLER = "BalanceAccountRequiredValidation.Controller"

typealias BalanceAccountRequiredValidation = AccountRequiredValidation<ManageStakingValidationPayload, ManageStakingValidationFailure>
typealias BalanceUnlockingLimitValidation = UnbondingRequestsLimitValidation<ManageStakingValidationPayload, ManageStakingValidationFailure>
