package io.novafoundation.nova.feature_staking_impl.presentation.mythos.start.selectCollatorSettings

import io.novafoundation.nova.common.navigation.InterScreenRequester
import io.novafoundation.nova.common.navigation.InterScreenResponder
import io.novafoundation.nova.feature_staking_impl.presentation.mythos.start.selectCollatorSettings.model.MythCollatorRecommendationConfigParcel

interface SelectMythCollatorSettingsInterScreenRequester : InterScreenRequester<MythCollatorRecommendationConfigParcel, MythCollatorRecommendationConfigParcel>
interface SelectMythCollatorSettingsInterScreenResponder : InterScreenResponder<MythCollatorRecommendationConfigParcel, MythCollatorRecommendationConfigParcel>

interface SelectMythCollatorSettingsInterScreenCommunicator : SelectMythCollatorSettingsInterScreenRequester, SelectMythCollatorSettingsInterScreenResponder
