name: Only test

on:
  pull_request:

jobs:
  test:
    name: Build app and test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Start SSH via tmate
        uses: P3TERX/ssh2actions@main
