name: Networks healthcheck

on:
  schedule:
    - cron: '0 10/5 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nova-wallet/build_tools:pr-3
      credentials:
        username: stepanLav
        password: ${{ secrets.GITHUB_TOKEN }}
      env:
        ACALA_PROD_AUTH_TOKEN: ${{ secrets.ACALA_PROD_AUTH_TOKEN }}
        ACALA_TEST_AUTH_TOKEN: ${{ secrets.ACALA_TEST_AUTH_TOKEN }}
        MOONBEAM_PROD_AUTH_TOKEN: ${{ secrets.MOONBEAM_PROD_AUTH_TOKEN }}
        MOONBEAM_TEST_AUTH_TOKEN: ${{ secrets.MOONBEAM_TEST_AUTH_TOKEN }}
        MOONPAY_PRODUCTION_SECRET: ${{ secrets.MOONPAY_PRODUCTION_SECRET }}
        MOONPAY_TEST_SECRET: ${{ secrets.MOONPAY_TEST_SECRET }}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop

      - name: Run test
        id: test
        continue-on-error: true
        run: ./gradlew -Dtest.single=NetworksAvailabilityTest test

      - name: Report
        if: steps.test.outcome=='failure'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}

            Repository: ${{ github.repository }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}