name: Manual Firebase distribution

on:
  workflow_dispatch:
     inputs:
      firebase_group:
        description: 'Firebase group'
        required: true
        default: dev-team

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - name: Set Environment Variables
        uses: tw3lveparsecs/github-actions-setvars@v0.1
        with:
          envFilePath: .github/workflows/variables/android.env

      - name: 🔧 Install dependencies
        uses: ./.github/workflows/install/

      - name: Run tests
        run: ./gradlew runTest

      - name: Build with Gradle
        run: ./gradlew assembleDevelop

      - uses: actions/upload-artifact@v2
        with:
          name: apk
          path: app/build/outputs/apk/develop/

  upload:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2
      - name: Download built artifact
        uses: actions/download-artifact@v2
        with:
          name: apk
          path: app

      - name: 🗳 Upload to Firebase
        uses: ./.github/workflows/upload-to-firebase
        with:
          appId: ${{ secrets.ANDROID_DEVELOP_FIREBASE_APP_ID }}
          firebase-token: ${{ secrets.ANDROID_DEV_FIREBASE_TOKEN }}
          releaseNotes: ${{ github.event.head_commit.message }}
          test-groups: ${{ github.event.inputs.firebase_group }}
          upload-file: app/app-develop.apk
