name: Pull request

on:
  pull_request:


jobs:
  test:
    uses: ./.github/workflows/reusable_android_build.yml
    with:
      gradlew-command: assembleDevelop
      build-debug-tests: false # TODO: Enable this, when debug build will be fixed for tests
    secrets: inherit
